# need the helm-cli from the helm image
FROM quay.io/openshift/origin-metering-helm:latest as helm
# final image needs kubectl, so we copy `oc` from cli image to use as kubectl.
FROM openshift/origin-cli:latest as cli
# real base
FROM quay.io/openshift/origin-ansible-operator:latest

USER root
RUN INSTALL_PKGS="curl bash ca-certificates less which inotify-tools openssl" \
    && yum -y install epel-release \
    && yum install --setopt=skip_missing_names_on_install=False -y \
        $INSTALL_PKGS  \
    && yum clean all \
    && rm -rf /var/cache/yum

ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

COPY --from=helm /usr/local/bin/helm /usr/local/bin/helm
COPY --from=cli /usr/bin/oc /usr/bin/oc
RUN ln -f -s /usr/bin/oc /usr/bin/kubectl
# put tini into our path
RUN ln -f -s /tini /usr/bin/tini

RUN pip install --no-cache-dir --upgrade openshift
RUN pip install boto3
RUN pip install pyOpenSSL

ENV HOME /opt/ansible
ENV HELM_CHART_PATH ${HOME}/charts/openshift-metering

COPY images/metering-ansible-operator/roles/ ${HOME}/roles/
COPY images/metering-ansible-operator/watches.yaml ${HOME}/watches.yaml
COPY images/metering-ansible-operator/scripts ${HOME}/scripts
COPY images/metering-ansible-operator/ansible.cfg /etc/ansible/ansible.cfg
COPY charts/openshift-metering ${HELM_CHART_PATH}

COPY manifests/deploy/openshift/olm/bundle /manifests

# to allow running as non-root
RUN chown -R 1001:0 $HOME && \
    chmod -R 774 $HOME /etc/passwd

USER 1001

ENTRYPOINT ["/opt/ansible/scripts/entrypoint.sh"]

LABEL io.k8s.display-name="OpenShift metering-ansible-operator" \
      io.k8s.description="This is a component of OpenShift Container Platform and manages installation and configuration of all other metering components." \
      io.openshift.tags="openshift" \
      com.redhat.delivery.appregistry=true \
      maintainer="Chance Zibolski <sd-operator-metering@redhat.com>"
