# need the helm-cli from the helm image
FROM registry.svc.ci.openshift.org/ocp/4.6:metering-helm as helm
# final image needs kubectl, so we copy `oc` from cli image to use as kubectl.
FROM registry.svc.ci.openshift.org/ocp/4.6:cli as cli
# need base-4.4 repo for boto python packages
FROM registry.svc.ci.openshift.org/ocp/4.4:base as base-4-4
# the base image is the ansible-operator's origin images
FROM registry.svc.ci.openshift.org/ocp/4.6:ansible-operator

USER root
RUN set -x;
ARG INSTALL_PKGS="less openssl tini python3-pip"

COPY --from=helm /usr/local/bin/helm /usr/local/bin/helm
COPY --from=cli /usr/bin/oc /usr/bin/oc
# the boto core packages will only install if the 4-4 repos are added w/out removing base repos
COPY --from=base-4-4 /etc/yum.repos.d/* /etc/yum.repos.d/

RUN yum install --verbose --allowerasing --setopt=skip_missing_names_on_install=False --nobest -y ${INSTALL_PKGS} \
    && yum clean all \
    && rm -rf /var/cache/yum

# put kubectl into our path
RUN ln -f -s /usr/bin/oc /usr/bin/kubectl

# List of python packages:
# 1. botocore and boto3 are used by the aws-related modules (aws_s3)
# 2. netaddr is needed to use the ipv4/ipv6 jinja filter
# 3. cryptography is used by the openssl_* modules for TLS/authentication purposes
RUN pip3 install --no-cache-dir --upgrade openshift botocore boto3 cryptography netaddr
# The ansible-operator base image will have Ansible installed by default and there's
# problems with running `pip install --upgrade` for upgrading to Ansible 2.10 from 2.9.
# This will ensure that we're always using a version of Ansible we've tested and contains
# the crypto.py FIPS fix as outlined in https://github.com/kube-reporting/metering-operator/issues/1444
RUN pip3 install --upgrade 'ansible>=2.9.6,<2.10'

ENV HOME /opt/ansible
ENV HELM_CHART_PATH ${HOME}/charts/openshift-metering

COPY images/metering-ansible-operator/roles/ ${HOME}/roles/
COPY images/metering-ansible-operator/watches.yaml ${HOME}/watches.yaml
COPY images/metering-ansible-operator/ansible.cfg /etc/ansible/ansible.cfg
COPY charts/openshift-metering ${HELM_CHART_PATH}

COPY manifests/deploy/openshift/olm/bundle /manifests

USER 1001

ENTRYPOINT ["tini", "--", "/usr/local/bin/ansible-operator", "exec-entrypoint", "ansible", "--watches-file", "/opt/ansible/watches.yaml"]

LABEL io.k8s.display-name="OpenShift metering-ansible-operator" \
    io.k8s.description="This is a component of OpenShift Container Platform and manages installation and configuration of all other metering components." \
    summary="This is a component of OpenShift Container Platform and manages installation and configuration of all other metering components." \
    io.openshift.tags="openshift" \
    com.redhat.delivery.appregistry=true \
    maintainer="<metering-team@redhat.com>"
