#!/bin/bash
set -e

: "${KUBECONFIG:?}"

ROOT_DIR=$(dirname "${BASH_SOURCE}")/..
source "${ROOT_DIR}/hack/common.sh"
source "${ROOT_DIR}/hack/lib/tests.sh"

# TODO: handle `make e2e-local`
# TODO: handle uninstall metering (maybe not namespace is not static)

export METERING_NAMESPACE="${METERING_E2E_NAMESPACE:=${METERING_NAMESPACE}-e2e}"
export TEST_LOG_FILE="${TEST_LOG_FILE:-e2e-tests.log}"
export DEPLOY_LOG_FILE="${DEPLOY_LOG_FILE:-e2e-deploy.log}"
export TEST_TAP_FILE="${TEST_TAP_FILE:-e2e-tests.tap}"

export TEST_OUTPUT_PATH="$(mktemp -d)"
export LOG_DIR=$TEST_OUTPUT_PATH/logs
export TEST_OUTPUT_DIR=$TEST_OUTPUT_PATH/tests
export REPORT_RESULTS_DIR=$TEST_OUTPUT_PATH/report_results
export METERINGCONFIGS_DIR=$TEST_OUTPUT_PATH/meteringconfigs
export REPORTS_DIR=$TEST_OUTPUT_PATH/reports
export DATASOURCES_DIR=$TEST_OUTPUT_PATH/reportdatasources
export REPORTQUERIES_DIR=$TEST_OUTPUT_PATH/reportqueries
export HIVETABLES_DIR=$TEST_OUTPUT_PATH/hivetables
export PRESTOTABLES_DIR=$TEST_OUTPUT_PATH/prestotables
export STORAGELOCATIONS_DIR=$TEST_OUTPUT_PATH/storagelocations
export TEST_RESULT_REPORT_OUTPUT_DIRECTORY=$TEST_OUTPUT_PATH/reports

mkdir -p "$LOG_DIR" "$TEST_OUTPUT_DIR" "$REPORT_RESULTS_DIR" "$METERINGCONFIGS_DIR" "$REPORTS_DIR" "$DATASOURCES_DIR" "$REPORTQUERIES_DIR" "$HIVETABLES_DIR" "$PRESTOTABLES_DIR" "$STORAGELOCATIONS_DIR"

export METERING_SHORT_TESTS=${METERING_SHORT_TESTS:-false}
export METERING_DEPLOY_MANIFESTS_PATH=${METERING_DEPLOY_MANIFESTS_PATH:-../../manifests/deploy}
export METERING_CLEANUP_SCRIPT_PATH=${METERING_CLEANUP_SCRIPT_PATH:-../../hack/run-test-cleanup.sh}
export METERING_HTTPS_API=${METERING_HTTPS_API:-true}
export METERING_USE_KUBE_PROXY_FOR_REPORTING_API=${METERING_USE_KUBE_PROXY_FOR_REPORTING_API:-false}
export METERING_USE_ROUTE_FOR_REPORTING_API=${METERING_USE_ROUTE_FOR_REPORTING_API:-true}
export METERING_REPORTING_API_URL=${METERING_REPORTING_API_URL:-""}

echo "\$KUBECONFIG=$KUBECONFIG"
echo "\$METERING_NAMESPACE=$METERING_NAMESPACE"
echo "\$METERING_OPERATOR_IMAGE_REPO=$METERING_OPERATOR_IMAGE_REPO"
echo "\$REPORTING_OPERATOR_IMAGE_REPO=$REPORTING_OPERATOR_IMAGE_REPO"
echo "\$METERING_OPERATOR_IMAGE_TAG=$METERING_OPERATOR_IMAGE_TAG"
echo "\$REPORTING_OPERATOR_IMAGE_TAG=$REPORTING_OPERATOR_IMAGE_TAG"

set -x
go test \
    -test.short="${METERING_SHORT_TESTS}" \
    -test.v \
    -parallel 10 \
    -timeout 25m \
    "./test/e2e" \
    -kubeconfig="${KUBECONFIG}" \
    -namespace-prefix="${METERING_NAMESPACE}" \
    -deploy-manifests-dir="${METERING_DEPLOY_MANIFESTS_PATH}" \
    -cleanup-script-path="${METERING_CLEANUP_SCRIPT_PATH}" \
    -https-api="${METERING_HTTPS_API}" \
    -use-kube-proxy-for-reporting-api="${METERING_USE_KUBE_PROXY_FOR_REPORTING_API}" \
    -use-route-for-reporting-api="${METERING_USE_ROUTE_FOR_REPORTING_API}" \
    -reporting-api-url="${METERING_REPORTING_API_URL}" \
    -log-level=debug \
    "$@"
