#!/bin/bash

function load_version_vars() {
    REAL_METERING_VERSION="$(cat "$ROOT_DIR/VERSION")"
    METERING_VERSION="${METERING_VERSION:-$REAL_METERING_VERSION}"
    DEVEL_LATEST_VERSION="${METERING_VERSION}-latest"
}
